package com.my.televip.obfuscate.resolve;

import com.my.televip.obfuscate.dex.CodeScanner;
import com.my.televip.obfuscate.dex.DexClass;
import com.my.televip.obfuscate.dex.DexFile;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * A fact about what a method's code does - which methods it calls, which fields it touches, which
 * strings and constants it loads. Used to tell apart members whose signatures alone are identical.
 *
 * <p>Facts are phrased in terms of other symbols' original names where possible, so they describe
 * the source rather than one build: "calls getStoriesFromFullPeer", not "calls y". A fact that
 * mentions a symbol not resolved yet answers null, which the resolver treats as "ask again later".</p>
 */
public interface Body {

    /** True or false, or null when it depends on something not resolved yet. */
    Boolean test(Resolver r, DexClass.Method method);

    // ------------------------------------------------------------- combinators

    static Body all(final Body... facts) {
        return (r, m) -> {
            for (Body f : facts) {
                Boolean b = f.test(r, m);
                if (b == null) return null;
                if (!b) return false;
            }
            return true;
        };
    }

    /** True if any fact holds; undecided while one could still decide it. */
    static Body any(final Body... facts) {
        return (r, m) -> {
            boolean undecided = false;
            for (Body f : facts) {
                Boolean b = f.test(r, m);
                if (b == null) undecided = true;
                else if (b) return true;
            }
            return undecided ? null : false;
        };
    }

    static Body not(final Body fact) {
        return (r, m) -> {
            Boolean b = fact.test(r, m);
            return b == null ? null : !b;
        };
    }

    // ------------------------------------------------------------------ facts

    /** Loads the given string constant. */
    static Body string(final String value) {
        return (r, m) -> Refs.of(r, m).strings.contains(value);
    }

    /** Loads the given integer constant. */
    static Body constant(final long value) {
        return (r, m) -> Refs.of(r, m).constants.contains(value);
    }

    /** Loads the given integer constant at least this many times. */
    static Body constantTimes(final long value, final int times) {
        return (r, m) -> {
            Integer n = Refs.of(r, m).constantLoads.get(value);
            return n != null && n >= times;
        };
    }

    /** Calls a method of its own class with this signature. */
    static Body callsSibling(final String returnType, final String... params) {
        return (r, m) -> {
            String proto = r.proto(returnType, params);
            if (proto == null) return null;
            for (Refs.Call c : Refs.of(r, m).calls) {
                if (c.owner.equals(m.owner.descriptor) && c.proto.equals(proto)) return true;
            }
            return false;
        };
    }

    /** Calls a method of {@code owner} named {@code name} (a name the build keeps), any signature. */
    static Body callsNamed(final String owner, final String name) {
        return (r, m) -> {
            String ownerDesc = r.descriptor(owner);
            if (ownerDesc == null) return null;
            for (Refs.Call c : Refs.of(r, m).calls) {
                if (c.owner.equals(ownerDesc) && c.name.equals(name)) return true;
            }
            return false;
        };
    }

    /** Calls a method of {@code owner} with this signature, whatever it is named. */
    static Body calls(final String owner, final String returnType, final String... params) {
        return (r, m) -> {
            String ownerDesc = r.descriptor(owner);
            String proto = r.proto(returnType, params);
            if (ownerDesc == null || proto == null) return null;
            for (Refs.Call c : Refs.of(r, m).calls) {
                if (c.owner.equals(ownerDesc) && c.proto.equals(proto)) return true;
            }
            return false;
        };
    }

    /** Calls the method another symbol resolved to, e.g. {@code "ChatActivity#createView"}. */
    static Body callsSymbol(final String methodSymbolId) {
        return (r, m) -> {
            DexClass.Method target = r.methods.get(methodSymbolId);
            // Undecided while the target may still resolve; a target that never did is not called.
            if (target == null) return r.isResolvedOrPending(methodSymbolId) ? null : false;
            String proto = Resolver.protoOf(target);
            for (Refs.Call c : Refs.of(r, m).calls) {
                if (c.owner.equals(target.owner.descriptor) && c.name.equals(target.name())
                        && c.proto.equals(proto)) return true;
            }
            return false;
        };
    }

    /** Written in the source, not generated by the compiler (a lambda body or an accessor). */
    static Body notSynthetic() {
        return (r, m) -> !m.isSynthetic();
    }

    /** Names a type in new-instance, check-cast, instance-of, const-class or an array op. */
    static Body refersTo(final String type) {
        return (r, m) -> {
            String desc = r.descriptor(type);
            if (desc == null) return null;
            return Refs.of(r, m).types.contains(desc);
        };
    }

    /** Reads or writes the field another symbol resolved to, e.g. {@code "MessagesController.dialogMessage"}. */
    static Body touchesFieldSymbol(final String fieldSymbolId) {
        return (r, m) -> {
            DexClass.Field target = r.fields.get(fieldSymbolId);
            if (target == null) return null;
            for (Refs.FieldRef f : Refs.of(r, m).fields) {
                if (f.owner.equals(target.owner.descriptor) && f.name.equals(target.name())) return true;
            }
            return false;
        };
    }

    /** Reads or writes a field of {@code owner} named {@code name} (a name the build keeps). */
    static Body touchesField(final String owner, final String name) {
        return (r, m) -> {
            String ownerDesc = r.descriptor(owner);
            // Renamed in builds where a field symbol describes it.
            String real = r.fieldName(owner, name);
            if (ownerDesc == null || real == null) return null;
            for (Refs.FieldRef f : Refs.of(r, m).fields) {
                if (f.owner.equals(ownerDesc) && f.name.equals(real)) return true;
            }
            return false;
        };
    }

    /** Calls any method with this name, on any class - for names the platform fixes. */
    static Body callsAnyNamed(final String name) {
        return (r, m) -> {
            for (Refs.Call c : Refs.of(r, m).calls) if (c.name.equals(name)) return true;
            return false;
        };
    }

    /** Makes exactly this many method calls. */
    static Body callCount(final int count) {
        return (r, m) -> Refs.of(r, m).calls.size() == count;
    }

    /** Contains this Dalvik opcode, e.g. 0xdf (xor-int/lit8) for a boolean negation. */
    static Body usesOpcode(final int opcode) {
        return (r, m) -> Refs.of(r, m).opcodes.contains(opcode);
    }

    /** Calls no method at all - a plain getter or setter. */
    static Body callsNothing() {
        return (r, m) -> Refs.of(r, m).calls.isEmpty();
    }

    /** Has a switch with this case key. */
    static Body switchKey(final int key) {
        return (r, m) -> Refs.of(r, m).switchKeys.contains(key);
    }

    /** Writes some field of {@code owner} whose type is {@code type}. */
    static Body writesFieldOfType(final String owner, final String type) {
        return (r, m) -> {
            String ownerDesc = r.descriptor(owner);
            String typeDesc = r.descriptor(type);
            if (ownerDesc == null || typeDesc == null) return null;
            for (Refs.FieldRef f : Refs.of(r, m).fields) {
                if (f.write && f.owner.equals(ownerDesc) && f.type.equals(typeDesc)) return true;
            }
            return false;
        };
    }

    /** Overrides a resolved method: same name (the signature is the symbol's own). */
    static Body overrides(final String methodSymbolId) {
        return (r, m) -> {
            DexClass.Method target = r.methods.get(methodSymbolId);
            if (target == null) return r.isResolvedOrPending(methodSymbolId) ? null : false;
            return m.name().equals(target.name()) && !m.owner.descriptor.equals(target.owner.descriptor);
        };
    }

    /** Is itself called by another (resolved) method - to pick one of look-alike helpers. */
    static Body calledBy(final String methodSymbolId) {
        return (r, m) -> {
            DexClass.Method caller = r.methods.get(methodSymbolId);
            if (caller == null) return null;
            String proto = Resolver.protoOf(m);
            for (Refs.Call c : Refs.of(r, caller).calls) {
                if (c.owner.equals(m.owner.descriptor) && c.name.equals(m.name()) && c.proto.equals(proto)) return true;
            }
            return false;
        };
    }

    /**
     * Creates a subclass of {@code base} and stores a {@code base} in a field of {@code owner} -
     * a lazily built {@code field = new FrameLayout(context) { ... }}, whether or not R8 narrowed
     * the field's type to the subclass.
     */
    static Body storesNewSubclassOf(final String owner, final String base) {
        return (r, m) -> {
            String ownerDesc = r.descriptor(owner);
            String baseDesc = r.descriptor(base);
            if (ownerDesc == null || baseDesc == null) return null;
            Refs refs = Refs.of(r, m);
            boolean stores = false;
            for (Refs.FieldRef f : refs.fields) {
                if (f.write && f.owner.equals(ownerDesc)
                        && (f.type.equals(baseDesc) || r.index.extendsClass(f.type, baseDesc))) stores = true;
            }
            if (!stores) return false;
            // R8 may or may not narrow the field to the subclass; the new-instance is there either way.
            for (String created : refs.newInstances) {
                if (!created.equals(baseDesc) && r.index.extendsClass(created, baseDesc)) return true;
            }
            return false;
        };
    }

    // ------------------------------------------------------------------- refs

    /** Everything one scan of a method yields, cached per method for the life of a resolution. */
    final class Refs {
        static final class Call {
            final String owner, name, proto;

            Call(String owner, String name, String proto) {
                this.owner = owner;
                this.name = name;
                this.proto = proto;
            }
        }

        static final class FieldRef {
            final String owner, name, type;
            final boolean write;

            FieldRef(String owner, String name, String type, boolean write) {
                this.owner = owner;
                this.name = name;
                this.type = type;
                this.write = write;
            }
        }

        final List<Call> calls = new ArrayList<>();
        final List<FieldRef> fields = new ArrayList<>();
        final Set<String> strings = new HashSet<>();
        final Set<Long> constants = new HashSet<>();
        final java.util.Map<Long, Integer> constantLoads = new java.util.HashMap<>();
        final Set<String> types = new HashSet<>();
        final List<String> newInstances = new ArrayList<>();
        final Set<Integer> switchKeys = new HashSet<>();
        final Set<Integer> opcodes = new HashSet<>();

        static Refs of(Resolver r, DexClass.Method method) {
            Refs cached = r.refs.get(method);
            if (cached != null) return cached;
            final Refs refs = new Refs();
            final DexFile dex = method.owner.dex;
            method.scan(new CodeScanner.Visitor() {
                @Override
                public void string(int i) {
                    refs.strings.add(dex.string(i));
                }

                @Override
                public void constant(long value) {
                    refs.constants.add(value);
                    Integer n = refs.constantLoads.get(value);
                    refs.constantLoads.put(value, n == null ? 1 : n + 1);
                }

                @Override
                public void invoke(int opcode, int i) {
                    int proto = dex.methodProto(i);
                    refs.calls.add(new Call(dex.methodClass(i), dex.methodName(i),
                            Resolver.protoOf(dex.protoReturnType(proto), dex.protoParameters(proto))));
                }

                @Override
                public void field(int opcode, int i, boolean write) {
                    refs.fields.add(new FieldRef(dex.fieldClass(i), dex.fieldName(i), dex.fieldType(i), write));
                }

                @Override
                public void type(int opcode, int i) {
                    refs.types.add(dex.type(i));
                    if (opcode == 0x22) refs.newInstances.add(dex.type(i));
                }

                @Override
                public void switchKey(int key) {
                    refs.switchKeys.add(key);
                }

                @Override
                public void opcode(int opcode) {
                    refs.opcodes.add(opcode);
                }
            });
            r.refs.put(method, refs);
            return refs;
        }

        @Override
        public String toString() {
            return "calls=" + calls.size() + " fields=" + fields.size()
                    + " strings=" + Arrays.toString(strings.toArray());
        }
    }
}
